/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-12-15")
public class CSLinkRequestMsg implements org.apache.thrift.TBase<CSLinkRequestMsg, CSLinkRequestMsg._Fields>, java.io.Serializable, Cloneable, Comparable<CSLinkRequestMsg> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CSLinkRequestMsg");

  private static final org.apache.thrift.protocol.TField OTHER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("otherId", org.apache.thrift.protocol.TType.I64, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CSLinkRequestMsgStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CSLinkRequestMsgTupleSchemeFactory();

  public long otherId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    OTHER_ID((short)1, "otherId");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // OTHER_ID
          return OTHER_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __OTHERID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.OTHER_ID, new org.apache.thrift.meta_data.FieldMetaData("otherId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CSLinkRequestMsg.class, metaDataMap);
  }

  public CSLinkRequestMsg() {
  }

  public CSLinkRequestMsg(
    long otherId)
  {
    this();
    this.otherId = otherId;
    setOtherIdIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CSLinkRequestMsg(CSLinkRequestMsg other) {
    __isset_bitfield = other.__isset_bitfield;
    this.otherId = other.otherId;
  }

  public CSLinkRequestMsg deepCopy() {
    return new CSLinkRequestMsg(this);
  }

  @Override
  public void clear() {
    setOtherIdIsSet(false);
    this.otherId = 0;
  }

  public long getOtherId() {
    return this.otherId;
  }

  public CSLinkRequestMsg setOtherId(long otherId) {
    this.otherId = otherId;
    setOtherIdIsSet(true);
    return this;
  }

  public void unsetOtherId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __OTHERID_ISSET_ID);
  }

  /** Returns true if field otherId is set (has been assigned a value) and false otherwise */
  public boolean isSetOtherId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __OTHERID_ISSET_ID);
  }

  public void setOtherIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __OTHERID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case OTHER_ID:
      if (value == null) {
        unsetOtherId();
      } else {
        setOtherId((java.lang.Long)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case OTHER_ID:
      return getOtherId();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case OTHER_ID:
      return isSetOtherId();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof CSLinkRequestMsg)
      return this.equals((CSLinkRequestMsg)that);
    return false;
  }

  public boolean equals(CSLinkRequestMsg that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_otherId = true;
    boolean that_present_otherId = true;
    if (this_present_otherId || that_present_otherId) {
      if (!(this_present_otherId && that_present_otherId))
        return false;
      if (this.otherId != that.otherId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(otherId);

    return hashCode;
  }

  @Override
  public int compareTo(CSLinkRequestMsg other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetOtherId()).compareTo(other.isSetOtherId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOtherId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.otherId, other.otherId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("CSLinkRequestMsg(");
    boolean first = true;

    sb.append("otherId:");
    sb.append(this.otherId);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CSLinkRequestMsgStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CSLinkRequestMsgStandardScheme getScheme() {
      return new CSLinkRequestMsgStandardScheme();
    }
  }

  private static class CSLinkRequestMsgStandardScheme extends org.apache.thrift.scheme.StandardScheme<CSLinkRequestMsg> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CSLinkRequestMsg struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // OTHER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.otherId = iprot.readI64();
              struct.setOtherIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CSLinkRequestMsg struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(OTHER_ID_FIELD_DESC);
      oprot.writeI64(struct.otherId);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CSLinkRequestMsgTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CSLinkRequestMsgTupleScheme getScheme() {
      return new CSLinkRequestMsgTupleScheme();
    }
  }

  private static class CSLinkRequestMsgTupleScheme extends org.apache.thrift.scheme.TupleScheme<CSLinkRequestMsg> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CSLinkRequestMsg struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetOtherId()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetOtherId()) {
        oprot.writeI64(struct.otherId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CSLinkRequestMsg struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.otherId = iprot.readI64();
        struct.setOtherIdIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

