/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-12-19")
public class SCRequestSerInfo implements org.apache.thrift.TBase<SCRequestSerInfo, SCRequestSerInfo._Fields>, java.io.Serializable, Cloneable, Comparable<SCRequestSerInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SCRequestSerInfo");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField SER_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("serInfo", org.apache.thrift.protocol.TType.MAP, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SCRequestSerInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SCRequestSerInfoTupleSchemeFactory();

  public long id; // required
  public java.util.Map<ClientInfoStruct,java.lang.String> serInfo; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    SER_INFO((short)2, "serInfo");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // SER_INFO
          return SER_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.SER_INFO, new org.apache.thrift.meta_data.FieldMetaData("serInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ClientInfoStruct.class), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SCRequestSerInfo.class, metaDataMap);
  }

  public SCRequestSerInfo() {
  }

  public SCRequestSerInfo(
    long id,
    java.util.Map<ClientInfoStruct,java.lang.String> serInfo)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.serInfo = serInfo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SCRequestSerInfo(SCRequestSerInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    if (other.isSetSerInfo()) {
      java.util.Map<ClientInfoStruct,java.lang.String> __this__serInfo = new java.util.HashMap<ClientInfoStruct,java.lang.String>(other.serInfo.size());
      for (java.util.Map.Entry<ClientInfoStruct, java.lang.String> other_element : other.serInfo.entrySet()) {

        ClientInfoStruct other_element_key = other_element.getKey();
        java.lang.String other_element_value = other_element.getValue();

        ClientInfoStruct __this__serInfo_copy_key = new ClientInfoStruct(other_element_key);

        java.lang.String __this__serInfo_copy_value = other_element_value;

        __this__serInfo.put(__this__serInfo_copy_key, __this__serInfo_copy_value);
      }
      this.serInfo = __this__serInfo;
    }
  }

  public SCRequestSerInfo deepCopy() {
    return new SCRequestSerInfo(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.serInfo = null;
  }

  public long getId() {
    return this.id;
  }

  public SCRequestSerInfo setId(long id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public int getSerInfoSize() {
    return (this.serInfo == null) ? 0 : this.serInfo.size();
  }

  public void putToSerInfo(ClientInfoStruct key, java.lang.String val) {
    if (this.serInfo == null) {
      this.serInfo = new java.util.HashMap<ClientInfoStruct,java.lang.String>();
    }
    this.serInfo.put(key, val);
  }

  public java.util.Map<ClientInfoStruct,java.lang.String> getSerInfo() {
    return this.serInfo;
  }

  public SCRequestSerInfo setSerInfo(java.util.Map<ClientInfoStruct,java.lang.String> serInfo) {
    this.serInfo = serInfo;
    return this;
  }

  public void unsetSerInfo() {
    this.serInfo = null;
  }

  /** Returns true if field serInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetSerInfo() {
    return this.serInfo != null;
  }

  public void setSerInfoIsSet(boolean value) {
    if (!value) {
      this.serInfo = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Long)value);
      }
      break;

    case SER_INFO:
      if (value == null) {
        unsetSerInfo();
      } else {
        setSerInfo((java.util.Map<ClientInfoStruct,java.lang.String>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case SER_INFO:
      return getSerInfo();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case SER_INFO:
      return isSetSerInfo();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof SCRequestSerInfo)
      return this.equals((SCRequestSerInfo)that);
    return false;
  }

  public boolean equals(SCRequestSerInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_serInfo = true && this.isSetSerInfo();
    boolean that_present_serInfo = true && that.isSetSerInfo();
    if (this_present_serInfo || that_present_serInfo) {
      if (!(this_present_serInfo && that_present_serInfo))
        return false;
      if (!this.serInfo.equals(that.serInfo))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(id);

    hashCode = hashCode * 8191 + ((isSetSerInfo()) ? 131071 : 524287);
    if (isSetSerInfo())
      hashCode = hashCode * 8191 + serInfo.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(SCRequestSerInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSerInfo()).compareTo(other.isSetSerInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSerInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.serInfo, other.serInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SCRequestSerInfo(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("serInfo:");
    if (this.serInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.serInfo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SCRequestSerInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SCRequestSerInfoStandardScheme getScheme() {
      return new SCRequestSerInfoStandardScheme();
    }
  }

  private static class SCRequestSerInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<SCRequestSerInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SCRequestSerInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.id = iprot.readI64();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SER_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                struct.serInfo = new java.util.HashMap<ClientInfoStruct,java.lang.String>(2*_map0.size);
                ClientInfoStruct _key1;
                java.lang.String _val2;
                for (int _i3 = 0; _i3 < _map0.size; ++_i3)
                {
                  _key1 = new ClientInfoStruct();
                  _key1.read(iprot);
                  _val2 = iprot.readString();
                  struct.serInfo.put(_key1, _val2);
                }
                iprot.readMapEnd();
              }
              struct.setSerInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SCRequestSerInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI64(struct.id);
      oprot.writeFieldEnd();
      if (struct.serInfo != null) {
        oprot.writeFieldBegin(SER_INFO_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRUCT, org.apache.thrift.protocol.TType.STRING, struct.serInfo.size()));
          for (java.util.Map.Entry<ClientInfoStruct, java.lang.String> _iter4 : struct.serInfo.entrySet())
          {
            _iter4.getKey().write(oprot);
            oprot.writeString(_iter4.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SCRequestSerInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SCRequestSerInfoTupleScheme getScheme() {
      return new SCRequestSerInfoTupleScheme();
    }
  }

  private static class SCRequestSerInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<SCRequestSerInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SCRequestSerInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetSerInfo()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetId()) {
        oprot.writeI64(struct.id);
      }
      if (struct.isSetSerInfo()) {
        {
          oprot.writeI32(struct.serInfo.size());
          for (java.util.Map.Entry<ClientInfoStruct, java.lang.String> _iter5 : struct.serInfo.entrySet())
          {
            _iter5.getKey().write(oprot);
            oprot.writeString(_iter5.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SCRequestSerInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.id = iprot.readI64();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TMap _map6 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRUCT, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.serInfo = new java.util.HashMap<ClientInfoStruct,java.lang.String>(2*_map6.size);
          ClientInfoStruct _key7;
          java.lang.String _val8;
          for (int _i9 = 0; _i9 < _map6.size; ++_i9)
          {
            _key7 = new ClientInfoStruct();
            _key7.read(iprot);
            _val8 = iprot.readString();
            struct.serInfo.put(_key7, _val8);
          }
        }
        struct.setSerInfoIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

